name = "lap"
version = "1.0.2"

description = "Quick'n dirty timing of your Gleam code."
licences = ["Apache-2.0"]
repository = { type = "github", user = "JosephTLyons", repo = "lap" }

[dependencies]
birl = ">= 1.8.0 and < 2.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
tobble = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
